# Generated by Django 4.2.3 on 2023-08-20 12:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True


    dependencies = [
        ('report', '0003_alter_dayreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('body', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('day_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 to='report.dayreport',
                                                 to_field="public_id")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
