# Generated by Django 4.2.3 on 2023-08-01 21:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')])),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('type_num', models.CharField(max_length=4, validators=[django.core.validators.MaxValueValidator(10)])),
                ('operation_num', models.CharField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('operation_name', models.CharField()),
                ('total_number_of_pieces', models.IntegerField()),
                ('min_norm', models.IntegerField()),
                ('total_hours', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dayreport',
            constraint=models.CheckConstraint(check=models.Q(('shift__in', ['morning', 'afternoon', 'night'])), name='report_dayreport_shift_valid'),
        ),
    ]
