# Generated by Django 4.2.3 on 2023-08-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayreport',
            options={'ordering': ['-date', '-start_time', '-end_time']},
        ),
        migrations.AlterField(
            model_name='dayreport',
            name='type_num',
            field=models.CharField(max_length=4),
        ),
    ]
