# Generated by Django 4.2.3 on 2023-08-20 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_dayreport_options_alter_dayreport_type_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayreport',
            options={'ordering': ['-start_date', '-start_time', '-end_time']},
        ),
        migrations.RenameField(
            model_name='dayreport',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='dayreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dayreport',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
