# Generated by Django 4.2.3 on 2023-10-01 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_rename_public_uuid_dayreport_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayreport',
            name='min_norm',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dayreport',
            name='total_hours',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dayreport',
            name='total_number_of_pieces',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='dayreport',
            constraint=models.CheckConstraint(check=models.Q(('total_hours__gte', 0)), name='report_dayreport_float_valid'),
        ),
    ]
